#!/bin/bash

# Usage:
# build-drums <file> <tempo>

echo "Building drums..."

# Create blank .wav file to start:

sox -n -c 1 temp1.wav trim 0.0 0.0

# start counter, iterate through lines

j=1
while read -r drum value; do

# Generate note samples

	./create-drums "$2"

# Append note to previous .wav file

	sox temp"$j".wav drum-"$drum"-"$value".wav temp"$((j+1))".wav &>/dev/null

# Delete previous .wav file

	rm temp"$j".wav

# Increment counter

	j=$((j+1))

# Get input from <file> provided

done < "$1"-drums

# Name our complete track

mv temp"$j".wav "$1"-drums.wav

# Make drum track length of bass track

songlen="$(soxi -D "$1"-bass.wav)"

# Create drum pattern

sox drum-k-8.wav drum-h-16.wav drum-h-16.wav drum-s-8.wav drum-h-16.wav drum-h-16.wav "$1"-drums.wav &>/dev/null

# Copy file repeatedly to loop it

sox "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums4.wav &>/dev/null
sox "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums16.wav &>/dev/null
sox "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums64.wav &>/dev/null

# Trim to length

sox "$1"-drums64.wav "$1"-drums64.wav "$1"-drums.wav trim 0 "$songlen" &>/dev/null

# Clean up samples

rm drum*.wav
rm "$1"-drums4.wav
rm "$1"-drums16.wav
rm "$1"-drums64.wav
