#!/bin/bash

# track builder extracted from mecca script
# file provided as first command line arg
# wave provided as second arg
# tempo provided as third arg

sox -n -c 1 temp1.wav trim 0.0 0.0
j=1
while read -r pitch value; do
	./create-notes "$pitch" "$2" "$3"
	sox temp"$j".wav note-"$pitch"-"$2"-"$value".wav temp"$((j+1))".wav
	rm temp"$j".wav
	j=$((j+1))
done < "$1"
mv temp"$j".wav "$1".wav
rm note*.wav