#!/bin/bash

# Usage:
# create-drums <tempo>

# Calculate note lengths from tempo

whole=$(bc <<< "scale = 10; (240 / $1)")
half=$(bc <<< "scale = 10; (120 / $1)")
quarter=$(bc <<< "scale = 10; (60 / $1)")
qtrip=$(bc <<< "scale = 10; (40 / $1)")
eighth=$(bc <<< "scale = 10; (30 / $1)")
etrip=$(bc <<< "scale = 10; (20 / $1)")
teenth=$(bc <<< "scale = 10; (15 / $1)")
ttrip=$(bc <<< "scale = 10; (10 / $1)")

et_less=$(bc <<< "scale = 10; ($half - $etrip)")
q_less=$(bc <<< "scale = 10; ($half - $qtrip)")
e_less=$(bc <<< "scale = 10; ($half - $eighth)")
t_less=$(bc <<< "scale = 10; ($half - $teenth)")

# Generate hi-hat samples

sox -n drum-h-1.wav synth 0.01 noise bass -5 fade 0 "$whole" "$whole" trim 0.0 "$whole" &>/dev/null
sox drum-h-1.wav drum-h-2.wav trim 0.0 "$half" &>/dev/null
sox drum-h-1.wav drum-h-4.wav trim 0 "$quarter" &>/dev/null
sox drum-h-1.wav drum-h-8.wav trim 0 "$eighth" &>/dev/null
sox drum-h-1.wav drum-h-16.wav trim 0 "$teenth" &>/dev/null

# snare

sox -n drum-s-1.wav synth 0.1 noise fade 0 "$whole" "$whole" trim 0 "$whole" &>/dev/null
sox drum-s-1.wav drum-s-2.wav trim 0 "$half" &>/dev/null
sox drum-s-1.wav drum-s-4.wav trim 0 "$quarter" &>/dev/null
sox drum-s-1.wav drum-s-8.wav trim 0 "$eighth" &>/dev/null
sox drum-s-1.wav drum-s-16.wav trim 0 "$teenth" &>/dev/null

# kick

sox -n drum-k-sine.wav synth 0.1 sine 50 trim 0 "$whole" &>/dev/null
sox -n drum-k-noise.wav synth 0.03 noise treble -15 fade 0 "$whole" "$whole" trim 0 "$whole" &>/dev/null
sox -m drum-k-sine.wav drum-k-noise.wav drum-k-1.wav gain 5 treble -15 &>/dev/null
sox drum-k-1.wav drum-k-2.wav trim 0 "$half" &>/dev/null
sox drum-k-1.wav drum-k-4.wav trim 0 "$quarter" &>/dev/null
sox drum-k-1.wav drum-k-8.wav trim 0 "$eighth" &>/dev/null
sox drum-k-1.wav drum-k-16.wav trim 0 "$teenth" &>/dev/null