#!/bin/bash

# Usage:
# drums <song> <tempo>

# Calculate note lengths from tempo

whole=$(bc <<< "scale = 10; (240 / $2)")
half=$(bc <<< "scale = 10; (120 / $2)")
quarter=$(bc <<< "scale = 10; (60 / $2)")
qtrip=$(bc <<< "scale = 10; (40 / $2)")
eighth=$(bc <<< "scale = 10; (30 / $2)")
etrip=$(bc <<< "scale = 10; (20 / $2)")
teenth=$(bc <<< "scale = 10; (15 / $2)")
ttrip=$(bc <<< "scale = 10; (10 / $2)")

et_less=$(bc <<< "scale = 10; ($half - $etrip)")
q_less=$(bc <<< "scale = 10; ($half - $qtrip)")
e_less=$(bc <<< "scale = 10; ($half - $eighth)")
t_less=$(bc <<< "scale = 10; ($half - $teenth)")

echo "Creating drum track..."

# Generate hi-hat samples

sox -n drum-h-whole.wav synth 0.01 noise fade 0 "$whole" "$whole" trim 0.0 "$whole" &>/dev/null
sox drum-h-whole.wav drum-h-half.wav trim 0.0 "$half"
sox drum-h-whole.wav drum-h-quarter.wav trim 0 "$quarter"
sox drum-h-whole.wav drum-h-eighth.wav trim 0 "$eighth"
sox drum-h-whole.wav drum-h-teenth.wav trim 0 "$teenth"

# snare

sox -n drum-s-1.wav synth 0.1 noise fade 0 "$whole" "$whole" trim 0 "$whole" &>/dev/null
sox drum-s-1.wav drum-s-2.wav trim 0 "$half" &>/dev/null
sox drum-s-1.wav drum-s-4.wav trim 0 "$quarter" &>/dev/null
sox drum-s-1.wav drum-s-8.wav trim 0 "$eighth" &>/dev/null
sox drum-s-1.wav drum-s-16.wav trim 0 "$teenth" &>/dev/null

# Make drum track length of bass track

songlen="$(soxi -D "$1"-bass.wav)"

# Create drum pattern

sox drum-h-8.wav drum-h-16.wav drum-h-16.wav drum-s-16.wav drum-h-16.wav drum-h-16.wav "$1"-drums.wav

# Copy file repeatedly to loop it

sox "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums4.wav
sox "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums16.wav
sox "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums64.wav

# Trim to length

sox "$1"-drums64.wav "$1"-drums64.wav "$1"-drums.wav trim 0 "$songlen"

# Clean up samples

rm drum*.wav
rm "$1"-drums4.wav
rm "$1"-drums16.wav
rm "$1"-drums64.wav
