#!/bin/bash

# song name is 1st arg
# tempo is 2nd arg

whole=$(bc <<< "scale = 10; (240 / $2)")
half=$(bc <<< "scale = 10; (120 / $2)")
quarter=$(bc <<< "scale = 10; (60 / $2)")
qtrip=$(bc <<< "scale = 10; (40 / $2)")
eighth=$(bc <<< "scale = 10; (30 / $2)")
etrip=$(bc <<< "scale = 10; (20 / $2)")
teenth=$(bc <<< "scale = 10; (15 / $2)")
ttrip=$(bc <<< "scale = 10; (10 / $2)")

et_less=$(bc <<< "scale = 10; ($half - $etrip)")
q_less=$(bc <<< "scale = 10; ($half - $qtrip)")
e_less=$(bc <<< "scale = 10; ($half - $eighth)")
t_less=$(bc <<< "scale = 10; ($half - $teenth)")

echo "Creating drum track..."
# hi-hat
sox -n drum-h-whole.wav synth 0.01 noise fade 0 "$whole" "$whole" trim 0.0 "$whole" &>/dev/null
sox drum-h-whole.wav drum-h-half.wav trim 0.0 "$half"
sox drum-h-whole.wav drum-h-quarter.wav trim 0 "$quarter"
sox drum-h-whole.wav drum-h-eighth.wav trim 0 "$eighth"
sox drum-h-whole.wav drum-h-teenth.wav trim 0 "$teenth"
# snare
sox -n drum-s-whole.wav synth 0.1 noise fade 0 "$whole" "$whole" trim 0 "$whole" &>/dev/null
sox drum-s-whole.wav drum-s-half.wav trim 0 "$half" &>/dev/null
sox drum-s-whole.wav drum-s-quarter.wav trim 0 "$quarter" &>/dev/null
sox drum-s-whole.wav drum-s-eighth.wav trim 0 "$eighth" &>/dev/null
sox drum-s-whole.wav drum-s-teenth.wav trim 0 "$teenth" &>/dev/null
# create pattern and loop it for length of song
songlen="$(soxi -D "$1"-bass.wav)"
sox drum-h-eighth.wav drum-h-teenth.wav drum-h-teenth.wav drum-s-eighth.wav drum-h-teenth.wav drum-h-teenth.wav "$1"-drums.wav
sox "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums.wav "$1"-drums4.wav
sox "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums4.wav "$1"-drums16.wav
sox "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums16.wav "$1"-drums64.wav
sox "$1"-drums64.wav "$1"-drums64.wav "$1"-drums.wav trim 0 "$songlen"
