#!/bin/bash

# Hide cursor

tput civis

./create-drums 120
echo "A = Kick"
echo "S = Snare"
echo "D = Hihat"
	
while true; do
	read -n1 key
	case $key in
		a) play drum-k-8.wav &>/dev/null & ;;
		s) play drum-s-8.wav &>/dev/null & ;;
		d) play drum-h-8.wav &>/dev/null & ;;
	esac
done
